name: Runs Proselint
on: push

jobs:
  proselint:
    name: Proselint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Proselint
        uses: ./
